# Generated by Django 6.0.3 on 2026-03-21 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredencialServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hipervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServidorFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_tag', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('ip_int', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_ext', models.GenericIPAddressField(blank=True, null=True)),
                ('cpu', models.IntegerField(blank=True, null=True)),
                ('memoria_ram', models.IntegerField(blank=True, null=True)),
                ('almacenamiento', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('sede', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.sede')),
            ],
            options={
                'ordering': ['service_tag'],
            },
        ),
        migrations.CreateModel(
            name='ServidorVirtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('a_cargo', models.CharField(blank=True, max_length=50)),
                ('ip_int', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_ext', models.GenericIPAddressField(blank=True, null=True)),
                ('dns_int', models.CharField(blank=True, max_length=300)),
                ('dns_ext', models.CharField(blank=True, max_length=300)),
                ('puertos_int', models.CharField(blank=True, max_length=100)),
                ('puertos_ext', models.CharField(blank=True, max_length=100)),
                ('mac_addres', models.CharField(blank=True, max_length=20)),
                ('cpu', models.IntegerField(blank=True, null=True)),
                ('memoria_ram', models.IntegerField(blank=True, null=True)),
                ('almacenamiento', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('hipervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.hipervisor')),
                ('sede', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.sede')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.servicio')),
                ('servidor_fisico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virtuales', to='inventario.servidorfisico')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SistemaOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='contacto',
        ),
        migrations.DeleteModel(
            name='Servidores_Fisicos',
        ),
        migrations.DeleteModel(
            name='Servidores_Virtuales',
        ),
        migrations.DeleteModel(
            name='usuariointerno',
        ),
        migrations.AddField(
            model_name='credencialservidor',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credenciales', to='inventario.servidorfisico'),
        ),
        migrations.AddField(
            model_name='servidorvirtual',
            name='sistema_operativo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.sistemaoperativo'),
        ),
        migrations.AddField(
            model_name='servidorfisico',
            name='sistema_operativo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.sistemaoperativo'),
        ),
    ]
