# Generated by Django 6.0.3 on 2026-03-25 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_credencialservidor_hipervisor_sede_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credencialservidor',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credenciales', to='inventario.servidorvirtual'),
        ),
    ]
