# Generated by Django 6.0.3 on 2026-03-29 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_credencialservidor_servidor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('SSH', 'SSH'), ('RDP', 'RDP'), ('BD', 'Base de datos')], max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='credencialservidor',
            name='servidor',
        ),
        migrations.AddField(
            model_name='credencialservidor',
            name='puerto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credencialservidor',
            name='servidor_fisico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credenciales', to='inventario.servidorfisico'),
        ),
        migrations.AddField(
            model_name='credencialservidor',
            name='servidor_virtual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credenciales', to='inventario.servidorvirtual'),
        ),
        migrations.AddField(
            model_name='servidorvirtual',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='documentos_servidores'),
        ),
        migrations.AddField(
            model_name='credencialservidor',
            name='tipo_acceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.tipoacceso'),
        ),
    ]
