# Generated by Django 5.2.12 on 2026-05-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_usuariosistema_credencialservidor_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoacceso',
            name='nombre',
            field=models.CharField(choices=[('SSH', 'SSH'), ('RDP', 'RDP'), ('LOCAL', 'Local'), ('IMora', 'Dominio'), ('BD', 'Base de datos')], max_length=10, unique=True),
        ),
    ]
