# Generated by Django 5.2.12 on 2026-05-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_tipoacceso_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credencialservidor',
            name='tipo_acceso',
            field=models.CharField(blank=True, choices=[('SSH', 'SSH'), ('RDP', 'RDP'), ('LOCAL', 'Local'), ('IMORA', 'Dominio'), ('BD', 'Base de Datos'), ('PHPMYADMIN', 'phpMyAdmin')], max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='TipoAcceso',
        ),
    ]
