# Generated by Django 5.2.12 on 2026-06-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_credencialservidor_tipo_acceso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credencialservidor',
            name='servidor_fisico',
        ),
        migrations.RemoveField(
            model_name='credencialservidor',
            name='servidor_virtual',
        ),
        migrations.AddField(
            model_name='credencialservidor',
            name='servidor_fisico',
            field=models.ManyToManyField(blank=True, related_name='credenciales', to='inventario.servidorfisico'),
        ),
        migrations.AddField(
            model_name='credencialservidor',
            name='servidor_virtual',
            field=models.ManyToManyField(blank=True, related_name='credenciales', to='inventario.servidorvirtual'),
        ),
    ]
