# Generated by Django 5.2.12 on 2026-06-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_remove_credencialservidor_servidor_fisico_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servidorfisico',
            old_name='ip_ext',
            new_name='ip_serv',
        ),
        migrations.AddField(
            model_name='servidorfisico',
            name='mac_addres',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
