# Generated by Django 6.0.3 on 2026-03-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipos_consulta', models.IntegerField(choices=[(0, 'Consulta'), (1, 'Reclamo'), (2, 'Sugerencia'), (3, 'Felicitacion')])),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Servidores_Fisicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_TAG', models.CharField(max_length=10, unique=True)),
                ('Nombre', models.CharField(max_length=124, unique=True)),
                ('O_S', models.CharField(choices=[('Microsoft Windows Server 2012 R2 Data Center', 'W S 2012 R2'), ('Microsoft Windows Server 2012', 'W S 2012'), ('Microsoft Windows Server 2008', 'W S 2008 R2'), ('Microsoft Windows Server 2008 R2', 'W S 2008 R2'), ('Microsoft Windows Server 2003 (32 Bits)', 'W S 2003'), ('Microsoft Windows XP Professional', 'W XP'), ('Microsoft Windows 7 (32 Bits)', 'W 7-32'), ('Microsoft Windows 7 (64 Bits)', 'W 7-64'), ('Microsoft Windows 8 (64 Bits)', 'W 8-64'), ('Centos (64-bits)', 'Centos'), ('Ubuntu (64 Bits)', 'Ubuntu'), ('Debian GNU/Linux (32 Bits)', 'Debian 32 Bits'), ('Debian GNU/Linux (64 Bits)', 'Debian 64 Bits'), ('OpenSuse 64 Bits', 'OpenSuse'), ('Suse Linux (64 Bits)', 'Suse linux'), ('Free BSD (32 Bits)', 'FreeBSD'), ('GuestOS', 'GuestOS'), ('Other Linux 32 Bits', 'Linux 32 Bits'), ('Other Linux 64 Bits', 'Linux 64'), ('Red Hat Enterprise 5 64 Bits', 'Red Hat Enterprise 5'), ('Red Hat Enterprise 6 64 Bits', 'Red Hat Enterprise 6')], default='W S 2012 R2', max_length=120)),
                ('A_cargo', models.CharField(blank=True, max_length=30, null=True)),
                ('Sede', models.CharField(choices=[('Plaza', 'Plaza'), ('Poussin', 'Poussin'), ('Bufalo', 'Bufalo'), ('Madrid', 'Madrid')], default='Plaza', max_length=20)),
                ('Servicio', models.CharField(blank=True, max_length=100, null=True)),
                ('IP_int', models.GenericIPAddressField(blank=True, default='10.1.1.1', null=True)),
                ('IP_ext', models.GenericIPAddressField(blank=True, default='10.1.1.1', null=True)),
                ('DNS_int', models.CharField(blank=True, max_length=100, null=True)),
                ('DNS_ext', models.CharField(blank=True, max_length=100, null=True)),
                ('Puertos_int', models.CharField(blank=True, max_length=200, null=True)),
                ('Puertos_ext', models.CharField(blank=True, max_length=200, null=True)),
                ('MAC_addres', models.CharField(blank=True, max_length=15, null=True)),
                ('CPU', models.IntegerField(blank=True, null=True)),
                ('Memoria_RAM', models.IntegerField(blank=True, null=True)),
                ('Almacenamiento', models.IntegerField(blank=True, null=True)),
                ('Descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Servidor Fisico',
                'verbose_name_plural': 'Servidores Fisicos',
                'ordering': ['Service_TAG'],
            },
        ),
        migrations.CreateModel(
            name='Servidores_Virtuales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hipervizor', models.CharField(choices=[('Hyper-V', 'Hyper-V'), ('Vmware', 'Vmware')], default='Vmware', max_length=10)),
                ('Nombre', models.CharField(max_length=124, unique=True)),
                ('O_S', models.CharField(choices=[('Microsoft Windows Server 2012 R2 Data Center', 'W S 2012 R2'), ('Microsoft Windows Server 2012', 'W S 2012'), ('Microsoft Windows Server 2008', 'W S 2008 R2'), ('Microsoft Windows Server 2008 R2', 'W S 2008 R2'), ('Microsoft Windows Server 2003 (32 Bits)', 'W S 2003'), ('Microsoft Windows XP Professional', 'W XP'), ('Microsoft Windows 7 (32 Bits)', 'W 7-32'), ('Microsoft Windows 7 (64 Bits)', 'W 7-64'), ('Microsoft Windows 8 (64 Bits)', 'W 8-64'), ('Centos (64-bits)', 'Centos'), ('Ubuntu (64 Bits)', 'Ubuntu'), ('Debian GNU/Linux (32 Bits)', 'Debian 32 Bits'), ('Debian GNU/Linux (64 Bits)', 'Debian 64 Bits'), ('OpenSuse 64 Bits', 'OpenSuse'), ('Suse Linux (64 Bits)', 'Suse linux'), ('Free BSD (32 Bits)', 'FreeBSD'), ('GuestOS', 'GuestOS'), ('Other Linux 32 Bits', 'Linux 32 Bits'), ('Other Linux 64 Bits', 'Linux 64'), ('Red Hat Enterprise 5 64 Bits', 'Red Hat Enterprise 5'), ('Red Hat Enterprise 6 64 Bits', 'Red Hat Enterprise 6')], default='W S 2012 R2', max_length=120)),
                ('A_cargo', models.CharField(blank=True, max_length=30, null=True)),
                ('Sede', models.CharField(choices=[('Plaza', 'Plaza'), ('Poussin', 'Poussin'), ('Bufalo', 'Bufalo'), ('Madrid', 'Madrid')], default='Plaza', max_length=20)),
                ('Servicio', models.CharField(blank=True, max_length=100, null=True)),
                ('IP_int', models.GenericIPAddressField(blank=True, default='10.1.1.1', null=True)),
                ('IP_ext', models.GenericIPAddressField(blank=True, default='10.1.1.1', null=True)),
                ('DNS_int', models.CharField(blank=True, max_length=200, null=True)),
                ('DNS_ext', models.CharField(blank=True, max_length=200, null=True)),
                ('Puertos_int', models.CharField(blank=True, max_length=100, null=True)),
                ('Puertos_ext', models.CharField(blank=True, max_length=100, null=True)),
                ('MAC_addres', models.CharField(blank=True, max_length=15, null=True)),
                ('CPU', models.IntegerField(blank=True, null=True)),
                ('Memoria_RAM', models.IntegerField(blank=True, null=True)),
                ('Almacenamiento', models.IntegerField(blank=True, null=True)),
                ('Descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Servidor Virtual',
                'verbose_name_plural': 'Servidores Virtuales',
                'ordering': ['Hipervizor'],
            },
        ),
        migrations.CreateModel(
            name='usuariointerno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_interno', models.CharField(max_length=50, null=True, verbose_name='Nombre de pila del usuario')),
                ('nombre_usuario', models.CharField(max_length=15)),
                ('password_usuario', models.CharField(max_length=10)),
                ('rol', models.CharField(choices=[('Redes', 'Redes'), ('Proyectos', 'Proyectos'), ('Masters', 'Infraestructura')], max_length=16)),
            ],
        ),
    ]
